spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb+srv://admin:sicredi@sicredi.38uge.mongodb.net/sicredi?retryWrites=true&w=majority

session.duration.default: 1
application:
  heroku:
    url: https://user-info.herokuapp.com
  config:
    timeout:
      connection: 500
      read: 500